### PR TITLE
 add gem caching to the importer job 

### PR DESCRIPTION
**Pull request by doudou**
Depends on:
- [x] https://github.com/rock-core/autoproj/pull/291

### CODE REVIEW

**Review by g-arjones — APPROVED** [review]

**Comment by doudou** [comment]
There has been a few meaningful changes since you review, could you re-review it please ?

**Review by g-arjones — APPROVED** [review]

**Comment by g-arjones** [comment]
Does not work on our server.. Some gems fail to compile and it's impossible to say why (we don't have access to the logs)

**Comment by g-arjones** [comment]
To be clear: it's the `import-cache` builder that does not work...

**Comment by doudou** [comment]
I just removed them from the list ... 

It seems that nokogiri is missing a dependency. debase as well (missing debase/ruby_core_source)

**Pull request merged**
