### PR TITLE
Test and cache size control

### PR DESCRIPTION
**Pull request by doudou**
Depends:
- [ ] https://github.com/rock-core/autoproj-ci/pull/8

### CODE REVIEW

**Comment by doudou** [comment]
@g-arjones not sure if you're using this still ...

**Comment by g-arjones** [comment]
Yeah.. Now I see why it's not done automatically in the plugin. Still, I would prefer to have it there, Any implications?

**Comment by doudou** [comment]
Well ... You need to pass the expected size, and you need to decide at what point in the build the cleanup should be done. For instance, could easily be done as a side worker instead of doing it within each build (same than with import cache).

A.k.a. this is a CI process. It's a workflow, and I consider that making these choices is part of building the workflow - i.e. part of system integration.

**Comment by g-arjones** [comment]
:+1:

**Pull request merged**
