### PR TITLE
working version with tests, cleaner python API and improved dashboard

### PR DESCRIPTION
**Pull request by doudou**
See the readme for a description of functionality.

### CODE REVIEW

**Comment by g-arjones** [comment]
Excellent stuff.. I have a question though: is there a practical way of testing the stuff in rock.py and dashboard.py other than triggering a build?

**Comment by doudou** [comment]
> is there a practical way of testing the stuff in rock.py and dashboard.py other than triggering a build?

no :(

**Review by g-arjones — APPROVED** [review]

**Comment by doudou** [comment]
I've been thinking about it this morning, and I don't see how you can meaningfully test `rock.py` without triggering a build (a test environment would be to have a set of builds that would test some pieces of the functionality and testing would be triggering all of them).

For `dashboard.py`, could unit-test some functions and then have a test environment with a set of build reports, each testing particular pieces of the UI.

**Comment by g-arjones** [comment]
Dashboard is less critical IMO, when I asked this I was wondering if buildbot itself wouldn't provide a mocking/stubbing harness to make that easier

**Pull request merged**
